# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: calme

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

custom:
  siteName: calme-dev-rosh2.com
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: static
      defaultContentType: text/html # optional 
      acl: public-read



# The `functions` block defines what code to deploy
# functions:
#   helloWorld:
#     handler: handler.helloWorld
#     # The `events` block defines how to trigger the handler.helloWorld code
#     events:
#       - http:
#           path: hello-world
#           method: get
#           cors: true

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]

plugins:
  - serverless-s3-sync
